root: "admin"
site-name: "Content Management System"
version: "1.3.1"
project: "elabra-classic"
page:
	index:
		login:
			title: "Secure Access - University of Missouri - School of Medicine"
			description: ""